Repository QuemMeAjuda/frontend, pull requests merged in 2018-07, with the labels that each got.

#18 Integration with backend
  src/app/app.module.ts
  src/app/app.routing.module.ts
  src/app/auth/user.ts
  src/app/help-details/help-details.component.css
  src/app/help-details/help-details.component.html
  src/app/help-details/help-details.component.ts
  src/app/home/ask-help/ask-help.component.ts
  src/app/home/home.component.html
  src/app/home/home.component.ts
  src/app/home/timeline/timeline.component.ts
  src/app/home/welcome/welcome.component.html
  src/app/home/welcome/welcome.component.ts
  src/app/home/welcome/welcome.service.spec.ts
  src/app/home/welcome/welcome.service.ts
  src/app/mock-system/mock-system.component.css
  src/app/mock-system/mock-system.component.html
  src/app/mock-system/mock-system.component.ts
  src/app/service/auth.service.ts
  src/app/service/help.service.ts
  src/app/service/user.service.ts
Labels: enhancement, feature

#19 Close help function
  src/app/app.module.ts
  src/app/design.module.ts
  src/app/help-details/bottom-sheet-overview-example-sheet.html
  src/app/help-details/help-details.component.css
  src/app/help-details/help-details.component.html
  src/app/help-details/help-details.component.ts
  src/app/home/home.component.html
  src/app/home/home.component.ts
  src/app/service/help.service.ts
Labels: feature

#20 Implementada a tela de detalhes do usuário
  src/app/app.module.ts
  src/app/app.routing.module.ts
  src/app/help-details/help-details.component.html
  src/app/help-details/help-details.component.ts
  src/app/service/user.service.ts
  src/app/user-details/user-details.component.css
  src/app/user-details/user-details.component.html
  src/app/user-details/user-details.component.spec.ts
  src/app/user-details/user-details.component.ts
Labels: feature

#21 Pagina do usuario quase finalizada
  src/app/help-details/help-details.component.html
  src/app/home/ask-help/ask-help.component.ts
  src/app/home/home.component.html
  src/app/home/home.component.ts
  src/app/user-details/user-details.component.html
  src/app/user-details/user-details.component.ts
Labels: enhancement

#22 Evaluation of user
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/design.module.ts
  src/app/help-details/bottom-sheet-overview-example-sheet.html
  src/app/help-details/dialog-overview-example-dialog.html
  src/app/help-details/help-details.component.html
  src/app/help-details/help-details.component.ts
  src/app/home/home.component.html
  src/app/service/help.service.ts
  src/app/service/user.service.ts
  src/app/user-details/user-details.component.html
  src/styles.css
Labels: feature

#23 Improving login and messages
  src/app/auth/auth.component.ts
  src/app/help-details/help-details.component.html
  src/app/home/timeline/timeline.component.html
  src/app/home/welcome/welcome.component.css
  src/app/home/welcome/welcome.component.html
  src/app/home/welcome/welcome.component.ts
  src/app/service/auth.service.ts
Labels: enhancement

#25 Finishing release
  src/app/app.module.ts
  src/app/app.routing.module.ts
  src/app/auth/auth.component.html
  src/app/auth/auth.component.ts
  src/app/error/error.component.css
  src/app/error/error.component.html
  src/app/error/error.component.spec.ts
  src/app/error/error.component.ts
  src/app/help-details/edit-help.html
  src/app/help-details/help-details.component.css
  src/app/help-details/help-details.component.html
  src/app/help-details/help-details.component.ts
  src/app/home/ask-help/ask-help.component.ts
  src/app/home/home.component.html
  src/app/home/home.component.ts
  src/app/rank-users/rank-users.component.css
  src/app/rank-users/rank-users.component.html
  src/app/rank-users/rank-users.component.spec.ts
  src/app/rank-users/rank-users.component.ts
  src/app/service/help.service.ts
  src/app/service/user.service.ts
  src/app/signup/signup.component.html
  src/app/signup/signup.component.ts
  src/app/tutor-register/tutor-register.component.html
  src/app/user-details/user-details.component.html
  src/app/user-details/user-details.component.ts
Labels: enhancement, feature

#26 Finishing release
  src/app/app.routing.module.ts
  src/app/home/timeline/timeline.component.html
Labels: bug, enhancement
