Repository QuemMeAjuda/frontend, pull requests merged in 2018-05, with the labels that each got.

#1 Authentication with firebase
  angular.json
  package-lock.json
  package.json
  src/app/app.component.html
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/app.routing.module.ts
  src/app/auth/auth.component.css
  src/app/auth/auth.component.html
  src/app/auth/auth.component.spec.ts
  src/app/auth/auth.component.ts
  src/app/auth/auth.guard.ts
  src/app/auth/auth.service.spec.ts
  src/app/auth/auth.service.ts
  src/app/auth/user.ts
  src/app/design.module.ts
  src/app/home/home.component.css
  src/app/home/home.component.html
  src/app/home/home.component.spec.ts
  src/app/home/home.component.ts
  src/environments/environment.prod.ts
  src/environments/environment.ts
  src/index.html
  src/main.ts
  src/styles.css
Labels: Feature

#2 Adding logo and brief description about the system
  src/app/auth/auth.component.css
  src/app/auth/auth.component.html
  src/app/auth/auth.component.ts
  src/app/home/home.component.html
  src/assets/images/quem_me_ajuda_logo.png
  src/index.html
  src/styles.css
Labels: enhancement

#3 Redesigning the login screen
  src/app/app.component.ts
  src/app/app.module.ts
  src/app/auth/auth.component.css
  src/app/auth/auth.component.html
  src/app/auth/auth.component.ts
  src/app/design.module.ts
  src/app/utils/utils.ts
  src/assets/icons/google_icon.svg
  src/assets/images/quem_me_ajuda_logo.png
  src/styles.css
Labels: enhancement

#4 Register as tutor
  src/app/app.module.ts
  src/app/tutor-register/tutor-register.component.css
  src/app/tutor-register/tutor-register.component.html
  src/app/tutor-register/tutor-register.component.spec.ts
  src/app/tutor-register/tutor-register.component.ts
Labels: feature

#5 Creating left-sidenavbar and make user info persistent.
  package-lock.json
  package.json
  src/app/app.module.ts
  src/app/auth/auth.component.ts
  src/app/auth/auth.service.ts
  src/app/auth/user.ts
  src/app/design.module.ts
  src/app/home/home.component.css
  src/app/home/home.component.html
  src/app/home/home.component.ts
  src/polyfills.ts
  src/styles.css
Labels: feature

#6 Tela de cadastro de ajudas
  src/app/app.module.ts
  src/app/app.routing.module.ts
  src/app/help-details/help-details.component.css
  src/app/help-model/help.ts
  src/app/home/ask-help/ask-help.component.css
  src/app/home/ask-help/ask-help.component.html
  src/app/home/ask-help/ask-help.component.spec.ts
  src/app/home/ask-help/ask-help.component.ts
  src/app/home/ask-help/ask-help.service.spec.ts
  src/app/home/ask-help/ask-help.service.ts
  src/app/home/home.component.html
  src/app/home/home.component.ts
  src/app/utils/utils.ts
Labels: enhancement

#9 Creating timeline to show all helps
  src/app/app.module.ts
  src/app/help-details/help-details.component.css
  src/app/help-details/help-details.component.html
  src/app/help-details/help-details.component.ts
  src/app/help-details/help.service.ts
  src/app/home/home.component.html
  src/app/home/home.component.ts
  src/app/home/timeline/timeline.component.css
  src/app/home/timeline/timeline.component.html
  src/app/home/timeline/timeline.component.spec.ts
  src/app/home/timeline/timeline.component.ts
Labels: feature

#10 Linking user and helps with backend
  src/app/app.module.ts
  src/app/app.routing.module.ts
  src/app/auth/auth.component.ts
  src/app/auth/auth.service.ts
  src/app/help-details/help-details.component.html
  src/app/help-details/help-details.component.ts
  src/app/help-details/help.service.ts
  src/app/home/ask-help/ask-help.component.html
  src/app/home/ask-help/ask-help.component.ts
  src/app/home/ask-help/ask-help.service.ts
  src/app/home/home.component.html
  src/app/home/home.component.ts
  src/app/service/user.service.spec.ts
  src/app/service/user.service.ts
  src/app/tutor-register/tutor-register.component.ts
  src/app/utils/utils.ts
Labels: enhancement

#11 Tela de inicio
  src/app/app.module.ts
  src/app/app.routing.module.ts
  src/app/home/ask-help/ask-help.component.ts
  src/app/home/ask-help/ask-help.service.spec.ts
  src/app/home/ask-help/ask-help.service.ts
  src/app/home/home.component.html
  src/app/home/welcome/welcome.component.css
  src/app/home/welcome/welcome.component.html
  src/app/home/welcome/welcome.component.spec.ts
  src/app/home/welcome/welcome.component.ts
  src/app/home/welcome/welcome.service.spec.ts
  src/app/home/welcome/welcome.service.ts
Labels: feature

#12 Signup
  src/app/app.module.ts
  src/app/app.routing.module.ts
  src/app/auth/auth.component.html
  src/app/auth/auth.component.ts
  src/app/design.module.ts
  src/app/signup/passwordValidation.component.ts
  src/app/signup/signup.component.css
  src/app/signup/signup.component.html
  src/app/signup/signup.component.spec.ts
  src/app/signup/signup.component.ts
Labels: feature

#13 fix design.module
  src/app/design.module.ts
Labels: bug
